### ISSUE TITLE
Rename global variable to Virgil in v5+

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#10]
Currently the global variable that is initialized when including the library as a script is called `virgil`.

This means that __currently__ initialization looks like this:

```js
var client = virgil.API("[ACCESS_TOKEN]");
```

It would be really nice if instead we could do this:

```js
var virgil = new Virgil("[ACCESS_TOKEN]");
// or, less preferable
var virgil = new Virgil.API("[ACCESS_TOKEN]");
```

With that in place, every SDK method call would start with `virgil.`, making it always clear to everyone which object is the Virgil client. 

As this is a backwards incompatible change, this should probably only be added from version 5 onwards.

**Comment by vadimavdeev** [comment]
The global variable name is now `Virgil`.
