### ISSUE TITLE
Allow saving of key without password

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#11]
Currently the SDK requires a password for saving the key, which I do not think is necessary, @unlim-it  agrees.

@vadimavdeev could we get this rolled out somewhere soon? I am working on a demo and would like to have this in it already.

**Comment by vadimavdeev** [comment]
@cbetta We can. Sometime this week.

**Comment by cbetta** [comment]
@vadimavdeev great, thanks. It would really be useful
