### ISSUE TITLE
Make key creation/loading/storing easier

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#13]
Currently I'm stuck in a bit of callback hell trying to do something pretty simple that most people will need to do:

* Load a key if it exists
* If it doesn't, generate a new key, store this key, and then return the new key

Currently, this looks as follows:

```js
function loadOrCreateKey(api, id, password, callback) {
  api.keys.load(id, password)
    .then(callback)
    .catch(function() {
      var key = api.keys.generate();
      key.save(id, password)
        .then(function () {
          callback(key);
        });
    });
}
```

This doesn't even include creating a card and sending it to the server.

I guess, Ideally I'd do something like this:

```js
api.keys.generateOrLoad(id, password)
  .then(function(key) {
     // now I have a problem: how do I know this is a new key?
  });
```

Not sure how to solve this problem, but would love for this to be a lot easier. 

Maybe a simpler solution would be to at least have a way to check if a key exists?

**Comment by vadimavdeev** [comment]
I agree that a method to check if key exists is needed. We'll add it soon. As well as resolving a Promise returned by `key.save` method with a key instance. As for your code - it can be simplified a bit by returning a `Promise` from your `loadOrCreateKey` method. Like this:

```javascript
function loadOrCreateKey(api, id, password) {
  return api.keys.load(id, password)
    .catch(function() {
        var key = api.keys.generate();
        return key.save(id, password)
            .then(function () {
                return key;
            });
    });
}
```

**Comment by vadimavdeev** [comment]
@cbetta You can now do this like this:
```javascript
function loadOrCreateKey(api, id, password) {
    return api.keys.exists(id)
        .then(function (keyExists) {
            if (keyExists) {
                return api.keys.load(id);
            }

            return api.keys.generate().save(id, password);
        });
}
```

**Comment by cbetta** [comment]
@vadimavdeev so in that case, how do I know if a key was created? I still need to create a card and publish it. 

I've been giving this a think and I think we can learn something from ORM. ActiveRecord has the ability to check if a record is a "new record", so if we translate that to this library ideally I'd like to be able to do this:

```js
api.keys.loadOrGenerate(id, password)
  .then(function(key) {
    if (key.isNew) { publishCard(key) }
    // continue doing other things
  };
```

**Comment by vadimavdeev** [comment]
@cbetta "new record" in active record means that this object hasn’t been saved yet. In your example the key is always saved. In my opinion, branching on `key.isNew` is no better than branching on `keyExists`. You're just saving some key strokes. Without the `loadOrGenerate` method it would be like this:

```javascript
api.keys.exists(id)
    .then(function (keyExists) {
        if (!keyExists) {
            api.keys.genereate().save(id, password)
            .then(function (key) {
                publishCard(key);
            });
        }
        // continue doing other things
    })
```

**Comment by cbetta** [comment]
@vadimavdeev sure thing, I know that in ActiveRecord it means it's not saved yet, but it's what inspired me ;)

As for saving some keystrokes, yes it does that, but it also lowers the cognitive load. 

Currently I have to __know__ to check if a key exists before I try to load it, or simply hope for loading to fail, and as a result I end up with very messy and indented code. You and I know this is a thing to remember, but we want to provide the easiest solution possible to customers, right?

The simplest solution I actually came to so far was this, which doesn't use the exist method:

```js
api.keys.load(id)
        .then(storeKeyInVar)
        .catch(createKeyAndCardAndTheStoreKeyInVar)
        .then(initUI);
```

By using the `then->catch->then` method the last `then` is always called, and in the previous `then->catch` I ensure `key` set to a var somewhere.

I guess my approach here is "try to load the key and handle failure", where yours is more "ensure they key exists and only then proceed".

**Comment by vadimavdeev** [comment]
Closing this because the API for working with keys has changed since v5.0.0
