### ISSUE TITLE
Question: should cards be cashed?

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#15]
My code is currently quite naive, looking up the sender's Card every time a message comes in. I wonder if there's a better way of doing this, maybe by caching the card and passing the card ID in the message?

Or is it cheap/fast/easy/desired/more secure to just keep calling Virgil?

**Comment by vadimavdeev** [comment]
I don't see any problem caching cards that you use frequently in memory. Calling Virgil is desired because it does integrity check by verifying signatures every time you fetch a card - unless you override this by providing a custom validator. As for cheap/fast/easy - that depends on your use case.

**Comment by cbetta** [comment]
@vadimavdeev as you said, checking every time does a signature check, and also ensures keys cards ares till valid. Cards can be removed (right?) and therefore should probably be loaded every time, or not?

**Comment by vadimavdeev** [comment]
@cbetta This again depends on your use case. For example, you can only load the cards on initialization and cache them in memory if you have a mechanism of notifying the clients that a card is added\removed. Like, in a chat app where the server side maintains a list of connected clients, the client side maintains a list of peers' Virgil Cards and the server notifies the clients when a member joins or leaves, providing their Virgil card identity (or ID).

**Comment by cbetta** [comment]
@vadimavdeev good point. Ok, for my demo I will keep it simple and just query every time, but it might be a great exercise.
