### ISSUE TITLE
Question: Passwordless Auth Support?

### ISSUE THREAD

**Issue by cbetta** [VirgilSecurity/virgil-sdk-javascript#16]
@vadimavdeev I am trying to write a guide for https://developer.virgilsecurity.com/docs/javascript/get-started/passwordless-authentication

Is this present in the JS SDK yet?

**Comment by vadimavdeev** [comment]
@cbetta Not yet, unfortunately.

**Comment by cbetta** [comment]
@vadimavdeev do you know which SDK has it already? Or alternatively, could you help me write some pseudo/fake JS code to show how it would probably work?

**Comment by vadimavdeev** [comment]
@cbetta For the moment, only [Objetive-C/Swift SDK](https://github.com/VirgilSecurity/virgil-sdk-x/tree/master/Source/Client) supports the [virgil-auth service](https://github.com/VirgilSecurity/virgil-services-auth). See `VSSAuthClient.h` and `VSSAuthServiceConfig.h`.

I have a sample node.js server that I've built for a demo, which "implements" OAuth2 and uses the virgil-auth service to obtain and refresh tokens. You can find it [here](https://github.com/vadimavdeev/fake-device-cloud). Feel free to ask if you need my help.

**Comment by cbetta** [comment]
@vadimavdeev can you add me on skype for some questions? `cristiano_betta`

**Comment by vadimavdeev** [comment]
@cbetta I've sent you a contact request.
