### ISSUE TITLE
When decrypting and verifying message, function returns array of numbers and not plaintext.

### ISSUE THREAD

**Issue by danwatco** [VirgilSecurity/virgil-sdk-javascript#18]
I have used virgil for encrypted communication and am having trouble with decrypting a message. The buffer returned by the decrypt function seems to have some sort of problem, when it is converted to a string using 'toString()' the value '[Object object]' is returned when it should return the original message. When tested locally the decryption works but when a server and socket communication is used, this is when the problems occur. Please could you assist.

The function in question is shown here`var originalMessage = userKey.decrypt(data.message.toString());
    console.log(originalMessage);` . The value of `originalMessage` is always "[Object object]" no matter what.

**Comment by vadimavdeev** [comment]
It looks like the `console.log` implementation does not call `toString` on the `originalMessage`. Try calling `toString` explicitly. Like this: 
`console.log(originalMessage.toString())`

**Comment by danwatco** [comment]
The code shown to log the variable is only currently being used for
debugging. Sorry I forgot to add, when adding the `.toString()` on the
variable, the output produces the string '[Object object]' not the
decrypted text.

Any more help?

**Comment by danwatco** [comment]
Sorry I didn't make it clear - when using the `.toString()` method on the `originalMessage` variable, the string '[Object object]' was produced. The logging is only currently being used for debugging

**Comment by vadimavdeev** [comment]
Could you provide some more context? Where is the `data` coming from? Where is it running (browser\node.js)? Which version of SDK are you using? Also, could you inspect in debugger what the `originalMessage` really is, or at least check what `JSON.stringify(originalMessage)` returns?

**Comment by danwatco** [comment]
The data is received from a socket event as below; It is a mess because I have been trying to debug the code. I was originally using the decrypt then verify function but was having problems with that too.

```
socket.on('recivedEncryptedMessage', function(data, callback){
  console.log('recived');
  console.log(data);
  Promise.all([
    vapi.keys.load(myUsername.toString(), password.toString()),
    vapi.cards.find(data.from.toString())
  ]).then(function(results) {
    var userKey = results[0];
    var fromCard = results[1];

    // var originalMessage = userKey.decryptThenVerify(message, fromCard);
    // console.log(originalMessage);

    var originalMessage = userKey.decrypt(data.message.toString());
    console.log(originalMessage);

    appendMessage(false, originalMessage.toString(), data.time);
  });
});
```

The message is encrypted using this function `var encryptedData = vapi.encryptFor(message.toString(), toCard).toString('base64');` and is then sent to a server using socket communication before being sent back to the client.
I am running this code on a local electron app. Using version 4.5.0 of the sdk.

**Comment by danwatco** [comment]
Using `JSON.stringify(originalMessage)` returns this value `{"type":"Buffer","data":[91,111,98,106,101,99,116,32,79,98,106,101,99,116,93]}`. The data is there but it is not converting to string?

**Comment by danwatco** [comment]
Was an issue with my own code. Sorry to confuse. No need for help.

**Comment by horeaporutiu** [comment]
@danwatco I am getting same problem..how did you solve this?

**Comment by horeaporutiu** [comment]
```
let response = await contract.submitTransaction('transaction1', 'hello');
    response = JSON.stringify(response)
    console.log('Response from invoking smart contract: ')
    console.log(response);
```
That is the code that is returning me the {type:buffer, data: [123.123...]} response.

**Comment by moneyeyedan** [comment]
i am getting data from mysql to node js,this format {"image":{"type":"Buffer","data":[91,111,98,106,101,99,116,32,79,98,106,101,99,116,93]}}.how to convert the base64 string format.
please help .

**Comment by vadimavdeev** [comment]
@moneyeyedan You can convert data into a string in base64 encoding _before_ storing them in database. With a `Buffer` object it's as easy as calling `toString('base64')` on it. For example, if you store some information encrypted with Virgil Crypto Library:

```js
const virgilCrypto = new VirgilCrypto();
const keypair = virgilCrypto.generateKeys();
const encryptedDataBuffer = virgilCrypto.encrypt('Text to encrypt', keypair.publicKey);
const encryptedDataString = encryptedDataBuffer.toString('base64');
// store the `encryptedDataString` in the database
```

Later you can load encrypted data from the database as a string and pass that to `virgilCrypto.decrypt` right away without converting to Buffer:

```js
const decryptedDataBuffer = virgilCrypto.decrypt(encryptedDataString, keypair.privateKey);
const decryptedDataString = decryptedDataBuffer.toString('utf8');
console.log(decryptedDataString); // prints 'Text to encrypt'
```
