### ISSUE TITLE
Nodejs runtime error

### ISSUE THREAD

**Issue by hyochan** [VirgilSecurity/virgil-sdk-javascript#66]
Followed the instruction [here](https://developer.virgilsecurity.com/docs/e3kit/get-started/generate-client-tokens) and below error throws in `"virgil-sdk": "^6.0.1"`.
```
 throw new Error("Cannot use global instances if the 'resetGlobalInstances' function has been called or 'createGlobalInstances' function has not been called yet.");
              ^
```

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/75268529-f5003380-583a-11ea-94cd-2f901ef3fa4b.png)

Here is [Sourcecode](https://github.com/dooboolab/hackatalk-server/blob/master/src/utils/virgil.ts).

**Comment by xlewkanx** [comment]
Hi @hyochan !

This snippet is slightly outdated, so thank you for pointing to this!

Starting from `virgil-crypto@4.0.0` you need to wait until `initCrypto` promise resolves before initiating `new VirgilCrypto()` instance.

Example code:
https://github.com/VirgilSecurity/virgil-crypto-javascript/blob/master/guides/usage-examples.md

**Comment by hyochan** [comment]
@xlwknx Thanks I've been suffering for this for an hour. Hope we have fresh document!
