### ISSUE TITLE
Provide mocking

### ISSUE THREAD

**Issue by hyochan** [VirgilSecurity/virgil-sdk-javascript#67]
I am suffering from writing `integration` testing using `virgil` sdk. How should I mock your sdk?
```
jest.mock('virgil-crypto');
jest.mock('virgil-sdk');
```

I need to mock them so I don't need actual credential from `virgil` to be uploaded to github.
![image](https://user-images.githubusercontent.com/27461460/75324579-a0040200-58ba-11ea-933d-65d927980c5c.png)

**Comment by hyochan** [comment]
I've tried to mock them myself, and I hope this can help someone using jest.
![image](https://user-images.githubusercontent.com/27461460/75325518-51effe00-58bc-11ea-9547-dfda5442beb7.png)

* virgil-sdk.ts
   ```
   export class JwtGenerator {
     private foo: string;
     constructor() {
       this.foo = 'bar';
     }

     generateToken = jest.fn().mockImplementation(() => ({
       toString: jest.fn(),
     }));
   }

   ```

* virgil-crypto.ts
   ```
   export class VirgilCrypto {
     private foo: string;
     constructor() {
       this.foo = 'bar';
     }

     public importPrivateKey = jest.fn();
   }

   export class VirgilAccessTokenSigner {
     private virgilCrypto: VirgilCrypto;
     constructor(virgilCrypto: VirgilCrypto) {
       this.virgilCrypto = virgilCrypto;
     }
   }

   export const initCrypto = jest.fn();
   ```


Now the test is passing.

**Comment by xlewkanx** [comment]
Hi, @hyochan !

Thank you for provided example and I'm glad to see that you have figured out how to handle jest mocks with virgil-sdk!

In Virgil we actually don't use mocks for testing our libraries. We use test credentials and never keep them in github. You can keep them as secret environment variables in your CI tool.

Mocking our library nothing differs from mocking other libraries. All I can recommend is to use [jest mocking guide](https://jestjs.io/docs/en/es6-class-mocks) and our [API reference](http://virgilsecurity.github.io/virgil-sdk-javascript/) to achieve your goals.

Happy coding!
