### ISSUE TITLE
How secure are private keys stored in the browser?

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-sdk-javascript#76]
https://github.com/VirgilSecurity/virgil-sdk-javascript/blob/49dc1250a34f64762f39329d3f527f578614a787/src/Storage/adapters/IndexedDbStorageAdapter.ts#L84

I'm trying to figure out how secure private keys are when using virgil (specifically e3kit) in the browser.  This line looks like it's stored in indexeddb.  Can it easily be extracted/exported?

If a malicious actor were to gain control over my website, could they deploy a new version that contains code that extracts the private key and sends it to themselves?

**Comment by xlewkanx** [comment]
Yes, virgil e3kit is uses IndexedDB and virgil storage secure as secure IndexedDB. So it has common vulnerabilities, like XSS attacks, code injection and especially if malicious actor were to gain control over your website he could still everything.

**Comment by camhart** [comment]
Thanks for answering!  Is it not possible to import the key in a way so that it cannot be exported (after it's already been backed up)?

**Comment by xlewkanx** [comment]
No, it is not possible.
